name: run-tests

# Only run this when the branch changes
on:
  push:

# This job installs dependencies, builds the code and runs the hand rolled Python test framework
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Install Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    # Install dependencies
    - name: Install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y libopenmpi-dev build-essential

    - name: Configure the code
      run: |
          cmake .
      
    - name: Build the GA library
      run: |
          make geneticAlgorithm

    - name: Build the circuit optimizer
      run: |
          make Circuit_Optimizer

    - name: Run the tests
      run: |
          make all
          ctest -VV